import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { Product } from '../../core/models/user.model';
import { ProductStorageService } from '../../core/services/product-storage.service';
import { StorageService } from '../../core/services/storage.service';
import { UNIT_CONFIGS, UnitConfig } from '../../core/constants/units.constants';

@Component({
  selector: 'app-add-product',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './add-product.component.html',
  styleUrls: ['./add-product.component.scss']
})
export class AddProductComponent implements OnInit {
  productForm!: FormGroup;
  availableUnits: UnitConfig[] = UNIT_CONFIGS;
  isSubmitting = false;
  errorMessage = '';
  selectedImagePreview: string | null = null;
  sellerMobileNumber: string = '';

  constructor(
    private fb: FormBuilder,
    private router: Router,
    private productStorageService: ProductStorageService,
    private storageService: StorageService
  ) {}

  ngOnInit(): void {
    // Get logged-in seller's mobile number
    this.sellerMobileNumber = this.storageService.getMobileNumber() || '';

    if (!this.sellerMobileNumber) {
      // Redirect to login if no mobile number found
      this.router.navigate(['/auth/mobile'], { queryParams: { role: 'farmer' } });
      return;
    }

    this.initForm();
  }

  /**
   * Initialize the form
   */
  private initForm(): void {
    this.productForm = this.fb.group({
      name: ['', [Validators.required, Validators.minLength(3)]],
      imageUrl: ['', [Validators.required]],
      currentStock: [0, [Validators.required, Validators.min(1)]],
      unit: ['kg', [Validators.required]],
      pricePerUnit: [0, [Validators.required, Validators.min(0.01)]]
    });
  }

  /**
   * Handle image file selection
   */
  onImageSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];

    if (!file) return;

    // Validate file type
    if (!file.type.startsWith('image/')) {
      this.errorMessage = 'Please select an image file';
      return;
    }

    // Validate file size (max 5MB)
    if (file.size > 5 * 1024 * 1024) {
      this.errorMessage = 'Image size must be less than 5MB';
      return;
    }

    // Convert to base64
    const reader = new FileReader();
    reader.onload = (e) => {
      const base64String = e.target?.result as string;
      this.selectedImagePreview = base64String;
      this.productForm.patchValue({ imageUrl: base64String });
      this.errorMessage = '';
    };
    reader.readAsDataURL(file);
  }

  /**
   * Calculate expected revenue
   */
  get expectedRevenue(): number {
    const stock = this.productForm.get('currentStock')?.value || 0;
    const price = this.productForm.get('pricePerUnit')?.value || 0;
    return stock * price;
  }

  /**
   * Get formatted expected revenue
   */
  get formattedExpectedRevenue(): string {
    return `₹${this.expectedRevenue.toLocaleString('en-IN')}`;
  }

  /**
   * Check if form field has error
   */
  hasError(field: string, error: string): boolean {
    const control = this.productForm.get(field);
    return !!(control && control.hasError(error) && (control.dirty || control.touched));
  }

  /**
   * Submit the form
   */
  onSubmit(): void {
    if (this.productForm.invalid) {
      this.productForm.markAllAsTouched();
      this.errorMessage = 'Please fill in all required fields';
      return;
    }

    this.isSubmitting = true;
    this.errorMessage = '';

    const formValue = this.productForm.value;

    // Create Product object
    const newProduct: Product = {
      productId: '', // Will be generated by service
      sellerMobileNumber: this.sellerMobileNumber,
      name: formValue.name,
      imageUrl: formValue.imageUrl,
      unit: formValue.unit,
      pricePerUnit: formValue.pricePerUnit,
      initialStock: formValue.currentStock,
      currentStock: formValue.currentStock,
      unitsSold: 0,
      createdDate: new Date().toISOString().split('T')[0]
    };

    // Add product to localStorage
    const success = this.productStorageService.addProduct(newProduct);

    if (success) {
      // Navigate back to dashboard
      this.router.navigate(['/seller']);
    } else {
      this.errorMessage = 'Failed to add product. Please try again.';
      this.isSubmitting = false;
    }
  }

  /**
   * Cancel and go back to dashboard
   */
  onCancel(): void {
    this.router.navigate(['/seller']);
  }
}
